### ISSUE TITLE
[OPT] Faire une refonte du projet front en terme de structure.

### ISSUE THREAD

**Issue by Feldrise** [Mydemenageur-Org/Mydemenageur-Site#1]
J'aimerai bien que soit décrit les changements principaux qui ont été fait afin de savoir ce qui a réellement changé, et éventuellement pouvoir former sur ce qui a été rajouté.

**Comment by LeoDELPON** [comment]
CHANGEMENTS DE LA STRUCTURE:
component/
|--atoms/ (considère ça comme les widgets que tu avais commencé à coder cad les buttons, input, dropdown etc...)
|
|--molecules/ (cela pourrait représenter par exemple un bloc article dans une section d'articles)
|
|--organisms/ (c'est là où l'on va mettre des sections d'une page)
|     |--landing/ (landing sections)
|     |--dashboard/ (dashboard sections)
|     |--demenageurs/ (demenageurs sections)
|--head.tsx (c'est un composant tsx pour les heads, cela permettra à l'avenir d'ajouter des metas si on en a besoin)
|--root.tsx (c'est le squelette de base de l'application)
|
constants/
|--app.ts (constants de l'application)
|--config.ts (constantes pour les services de l'API)
|--rest.ts (constantes pour l'api)
|
actions/
|--actionTypes/
|      |--actionTypes.ts (les types d'actions)
|--auth.action.ts (représente l'action de l'auth)
|--... 
|
models/
|--props/ (dossiers pour les interfaces de props d'un composant TSX)
|
|--states/ (dossier pour les interfaces des états hook d'un composant TSX)
|--picture.tsx (model classique)
|--... 
|
utils/ (ce sont les functions helpers)
|
services/ (c'est pour les services aka les requêtes vers l'API ou autres)
|
reducers/ (cela correspond aux reducers redux) 
|
sagas/ (c'est pour redux-saga)
|
font/ (c'est là où sont stockés les fonts)
|
mock/ (c'est un dossier pour tester les composants tsx. Il sera supprimé quand redux aura été mis en place)
|
styles/ 
|
|--tailwind.config.js (c'est un file pour la configuration tailwind)
|--postcss.config.js (fichier de confi css pour le bundle)

AJOUTS DE CONVENTIONS:

- Lorsque l'on crée un composant dans atoms, on associera en plus des énumérations pour éviter que les futurs développeurs fassent des erreurs. Il y aura juste à call les enums.
- Il faudra utiliser le plus possible tailwind.css pour la performance de l'application.
- Le composant Image de next permet le lazy loading mais il n'est pas nécessaire pour tout, il faudra débattre sur ce point ci sur 
la pertinence de ce composant pour l'implémentation d'images de bases telles que des svg button par exemple.

LES CHANGEMENTS NOTABLES:
- Mise en pratique du SOC.
- La landing page refaite.
- La max width bloquée à 1440px

POINTS PAS ENCORE FAIT:
- le responsive mobile et ipad;
- clean du code complet
