### ISSUE TITLE
[FEAT] Advanced search

### ISSUE THREAD

**Issue by suiramdev** [Mydemenageur-Org/Mydemenageur-Site#69]
This feature adds an auto-complete entry on the searchBtnBar to help people find their city.
For now, when the player submits a search it increments the city's search count by one so it is displayed on top of the others.

> Requires the advanced-search features on the API too.

**Comment by Feldrise** [comment]
I need to try with pushing the API

**Comment by suiramdev** [comment]
Problem solved, apparently there were some cities without `label` in the prod. I added a check for `label`.
